@extends('layouts.app')

@section('title', 'Gantt Chart - Project Management')

@section('content')
<div class="space-y-6">
    <!-- Page Header -->
    <div class="flex justify-between items-center">
        <div>
            <h1 class="text-2xl font-bold text-gray-900">Gantt Chart</h1>
            <p class="text-gray-500">Visualize project timeline and dependencies</p>
        </div>
        <div class="flex space-x-3">
            <button onclick="openAddTaskModal()" class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center space-x-2">
                <svg class="w-4 h-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
                </svg>
                <span class="whitespace-nowrap">Add Task</span>
            </button>
            <button onclick="exportGantt()" class="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 flex items-center space-x-2">
                <svg class="w-4 h-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/>
                </svg>
                <span class="whitespace-nowrap">Export</span>
            </button>
            <button onclick="refreshGantt()" class="px-4 py-2 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 flex items-center space-x-2">
                <svg class="w-4 h-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m0 0l3 9m-3-9v12m0 0l-3-9m3 9H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"/>
                </svg>
                <span class="whitespace-nowrap">Refresh</span>
            </button>
        </div>
    </div>

    <!-- Gantt Controls -->
    <div class="bg-white rounded-lg shadow p-6">
        <div class="flex items-center justify-between mb-6">
            <div class="flex items-center space-x-4">
                <select class="border border-gray-300 rounded-lg px-3 py-2" onchange="changeProject(this.value)">
                    <option value="project1">Project Alpha</option>
                    <option value="project2">Project Beta</option>
                    <option value="project3">Project Gamma</option>
                </select>
                <select class="border border-gray-300 rounded-lg px-3 py-2" onchange="changeView(this.value)">
                    <option value="week">Week View</option>
                    <option value="month">Month View</option>
                    <option value="quarter">Quarter View</option>
                </select>
                <div class="flex items-center space-x-2">
                    <button onclick="zoomIn()" class="px-2 py-1 bg-gray-100 text-gray-700 rounded hover:bg-gray-200">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0zM10 7v6m3-3H7"/>
                        </svg>
                    </button>
                    <button onclick="zoomOut()" class="px-2 py-1 bg-gray-100 text-gray-700 rounded hover:bg-gray-200">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0zM13 10H7"/>
                        </svg>
                    </button>
                </div>
            </div>
            <div class="flex items-center space-x-2">
                <button onclick="toggleCriticalPath()" class="px-3 py-1 bg-orange-100 text-orange-700 rounded-lg hover:bg-orange-200 text-sm">
                    Critical Path
                </button>
                <button onclick="toggleDependencies()" class="px-3 py-1 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 text-sm">
                    Dependencies
                </button>
            </div>
        </div>

        <!-- Gantt Chart -->
        <div class="overflow-x-auto">
            <div class="min-w-[1200px]">
                <!-- Timeline Header -->
                <div class="flex border-b-2 border-gray-300">
                    <div class="w-64 p-3 bg-gray-50 border-r border-gray-300">
                        <h3 class="font-semibold text-gray-900">Task</h3>
                    </div>
                    <div class="flex-1 flex" id="timeline-header">
                        <!-- Timeline will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Gantt Rows -->
                <div id="gantt-rows">
                    <!-- Task rows will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>

    <!-- Project Statistics -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div class="bg-white rounded-lg shadow p-6">
            <div class="flex items-center">
                <div class="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <svg class="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"/>
                    </svg>
                </div>
                <div class="ml-4">
                    <p class="text-sm text-gray-500">Total Tasks</p>
                    <p class="text-2xl font-semibold text-gray-900" id="total-tasks">24</p>
                </div>
            </div>
        </div>

        <div class="bg-white rounded-lg shadow p-6">
            <div class="flex items-center">
                <div class="w-10 h-10 bg-green-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <svg class="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                    </svg>
                </div>
                <div class="ml-4">
                    <p class="text-sm text-gray-500">Completed</p>
                    <p class="text-2xl font-semibold text-gray-900" id="completed-tasks">8</p>
                </div>
            </div>
        </div>

        <div class="bg-white rounded-lg shadow p-6">
            <div class="flex items-center">
                <div class="w-10 h-10 bg-yellow-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <svg class="w-5 h-5 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>
                    </svg>
                </div>
                <div class="ml-4">
                    <p class="text-sm text-gray-500">In Progress</p>
                    <p class="text-2xl font-semibold text-gray-900" id="progress-tasks">12</p>
                </div>
            </div>
        </div>

        <div class="bg-white rounded-lg shadow p-6">
            <div class="flex items-center">
                <div class="w-10 h-10 bg-red-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <svg class="w-5 h-5 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
                    </svg>
                </div>
                <div class="ml-4">
                    <p class="text-sm text-gray-500">Overdue</p>
                    <p class="text-2xl font-semibold text-gray-900" id="overdue-tasks">4</p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Add Task Modal -->
<div id="addTaskModal" class="fixed inset-0 bg-black bg-opacity-50 hidden flex items-center justify-center z-50">
    <div class="bg-white rounded-lg p-6 w-full max-w-md">
        <h3 class="text-lg font-semibold text-gray-900 mb-4">Add New Task</h3>
        <form id="addTaskForm">
            <div class="space-y-4">
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Task Name</label>
                    <input type="text" name="name" class="w-full border border-gray-300 rounded-lg px-3 py-2" required>
                </div>
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Assignee</label>
                    <select name="assignee" class="w-full border border-gray-300 rounded-lg px-3 py-2">
                        <option value="John Doe">John Doe</option>
                        <option value="Jane Smith">Jane Smith</option>
                        <option value="Mike Johnson">Mike Johnson</option>
                        <option value="Sarah Wilson">Sarah Wilson</option>
                    </select>
                </div>
                <div class="grid grid-cols-2 gap-4">
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">Start Date</label>
                        <input type="date" name="start_date" class="w-full border border-gray-300 rounded-lg px-3 py-2" required>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">End Date</label>
                        <input type="date" name="end_date" class="w-full border border-gray-300 rounded-lg px-3 py-2" required>
                    </div>
                </div>
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Progress (%)</label>
                    <input type="number" name="progress" min="0" max="100" class="w-full border border-gray-300 rounded-lg px-3 py-2" value="0">
                </div>
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Dependencies</label>
                    <select name="dependencies" class="w-full border border-gray-300 rounded-lg px-3 py-2" multiple>
                        <option value="task1">Task 1</option>
                        <option value="task2">Task 2</option>
                        <option value="task3">Task 3</option>
                    </select>
                </div>
            </div>
            <div class="flex justify-end space-x-3 mt-6">
                <button type="button" onclick="closeAddTaskModal()" class="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300">Cancel</button>
                <button type="submit" class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">Add Task</button>
            </div>
        </form>
    </div>
</div>
@endsection

@section('scripts')
<script>
// Sample task data
const tasks = [
    {
        id: 1,
        name: 'Project Planning',
        assignee: 'John Doe',
        start_date: '2024-05-01',
        end_date: '2024-05-05',
        progress: 100,
        dependencies: [],
        color: 'bg-blue-500'
    },
    {
        id: 2,
        name: 'Design Phase',
        assignee: 'Jane Smith',
        start_date: '2024-05-06',
        end_date: '2024-05-12',
        progress: 75,
        dependencies: [1],
        color: 'bg-purple-500'
    },
    {
        id: 3,
        name: 'Development Sprint 1',
        assignee: 'Mike Johnson',
        start_date: '2024-05-13',
        end_date: '2024-05-20',
        progress: 50,
        dependencies: [2],
        color: 'bg-green-500'
    },
    {
        id: 4,
        name: 'Testing Phase',
        assignee: 'Sarah Wilson',
        start_date: '2024-05-21',
        end_date: '2024-05-25',
        progress: 25,
        dependencies: [3],
        color: 'bg-yellow-500'
    },
    {
        id: 5,
        name: 'Deployment',
        assignee: 'John Doe',
        start_date: '2024-05-26',
        end_date: '2024-05-30',
        progress: 0,
        dependencies: [4],
        color: 'bg-red-500'
    }
];

let currentView = 'week';
let showCriticalPath = false;
let showDependencies = true;

function initializeGantt() {
    generateTimeline();
    generateGanttRows();
    updateStatistics();
}

function generateTimeline() {
    const header = document.getElementById('timeline-header');
    header.innerHTML = '';
    
    const startDate = new Date('2024-05-01');
    const endDate = new Date('2024-05-31');
    const days = Math.ceil((endDate - startDate) / (1000 * 60 * 60 * 24));
    
    for (let i = 0; i <= days; i++) {
        const currentDate = new Date(startDate);
        currentDate.setDate(startDate.getDate() + i);
        
        const dayDiv = document.createElement('div');
        dayDiv.className = 'flex-1 min-w-[40px] p-2 text-center border-r border-gray-200 bg-gray-50';
        dayDiv.innerHTML = `
            <div class="text-xs font-medium text-gray-900">${currentDate.getDate()}</div>
            <div class="text-xs text-gray-500">${currentDate.toLocaleDateString('en', { weekday: 'short' })}</div>
        `;
        header.appendChild(dayDiv);
    }
}

function generateGanttRows() {
    const rowsContainer = document.getElementById('gantt-rows');
    rowsContainer.innerHTML = '';
    
    tasks.forEach(task => {
        const row = createTaskRow(task);
        rowsContainer.appendChild(row);
    });
}

function createTaskRow(task) {
    const row = document.createElement('div');
    row.className = 'flex border-b border-gray-200';
    
    // Task info column
    const taskInfo = document.createElement('div');
    taskInfo.className = 'w-64 p-3 bg-white border-r border-gray-200';
    taskInfo.innerHTML = `
        <div class="font-medium text-gray-900">${task.name}</div>
        <div class="text-sm text-gray-500">${task.assignee}</div>
        <div class="text-xs text-gray-400 mt-1">${task.progress}% Complete</div>
    `;
    
    // Timeline column
    const timeline = document.createElement('div');
    timeline.className = 'flex-1 flex relative bg-gray-50';
    timeline.id = `timeline-${task.id}`;
    
    // Calculate task position and width
    const startDate = new Date('2024-05-01');
    const taskStart = new Date(task.start_date);
    const taskEnd = new Date(task.end_date);
    
    const startOffset = Math.ceil((taskStart - startDate) / (1000 * 60 * 60 * 24));
    const duration = Math.ceil((taskEnd - taskStart) / (1000 * 60 * 60 * 24)) + 1;
    
    // Create task bar
    const taskBar = document.createElement('div');
    taskBar.className = `absolute ${task.color} rounded-md h-6 flex items-center justify-center text-white text-xs font-medium cursor-pointer hover:opacity-80`;
    taskBar.style.left = `${startOffset * 40}px`;
    taskBar.style.width = `${duration * 40}px`;
    taskBar.style.top = '12px';
    taskBar.innerHTML = `${task.progress}%`;
    taskBar.onclick = () => showTaskDetails(task);
    
    // Add progress bar
    const progressBar = document.createElement('div');
    progressBar.className = 'absolute bg-black bg-opacity-20 rounded-md h-6';
    progressBar.style.left = `${startOffset * 40}px`;
    progressBar.style.width = `${duration * 40}px`;
    progressBar.style.top = '12px';
    
    const progressFill = document.createElement('div');
    progressFill.className = 'bg-green-400 rounded-md h-6';
    progressFill.style.width = `${(task.progress / 100) * 100}%`;
    progressBar.appendChild(progressFill);
    
    timeline.appendChild(progressBar);
    timeline.appendChild(taskBar);
    
    // Add dependency lines if enabled
    if (showDependencies && task.dependencies.length > 0) {
        task.dependencies.forEach(depId => {
            const depLine = createDependencyLine(depId, task.id);
            timeline.appendChild(depLine);
        });
    }
    
    row.appendChild(taskInfo);
    row.appendChild(timeline);
    
    return row;
}

function createDependencyLine(fromTaskId, toTaskId) {
    // This is a simplified version - in a real implementation, you'd calculate actual coordinates
    const line = document.createElement('div');
    line.className = 'absolute bg-purple-400';
    line.style.width = '2px';
    line.style.height = '20px';
    line.style.left = '100px';
    line.style.top = '30px';
    line.style.transform = 'rotate(45deg)';
    return line;
}

function updateStatistics() {
    const totalTasks = tasks.length;
    const completedTasks = tasks.filter(t => t.progress === 100).length;
    const progressTasks = tasks.filter(t => t.progress > 0 && t.progress < 100).length;
    const overdueTasks = tasks.filter(t => {
        const today = new Date();
        const endDate = new Date(t.end_date);
        return t.progress < 100 && endDate < today;
    }).length;
    
    document.getElementById('total-tasks').textContent = totalTasks;
    document.getElementById('completed-tasks').textContent = completedTasks;
    document.getElementById('progress-tasks').textContent = progressTasks;
    document.getElementById('overdue-tasks').textContent = overdueTasks;
}

function openAddTaskModal() {
    document.getElementById('addTaskModal').classList.remove('hidden');
}

function closeAddTaskModal() {
    document.getElementById('addTaskModal').classList.add('hidden');
    document.getElementById('addTaskForm').reset();
}

function showTaskDetails(task) {
    alert(`Task: ${task.name}\nAssignee: ${task.assignee}\nProgress: ${task.progress}%\nDates: ${task.start_date} to ${task.end_date}`);
}

function exportGantt() {
    showNotification('Gantt chart exported successfully!', 'success');
}

function refreshGantt() {
    initializeGantt();
    showNotification('Gantt chart refreshed!', 'info');
}

function changeProject(project) {
    console.log('Changed to project:', project);
    // In a real app, this would load different project data
}

function changeView(view) {
    currentView = view;
    initializeGantt();
    console.log('Changed view to:', view);
}

function zoomIn() {
    showNotification('Zoomed in', 'info');
}

function zoomOut() {
    showNotification('Zoomed out', 'info');
}

function toggleCriticalPath() {
    showCriticalPath = !showCriticalPath;
    showNotification(`Critical path ${showCriticalPath ? 'shown' : 'hidden'}`, 'info');
}

function toggleDependencies() {
    showDependencies = !showDependencies;
    generateGanttRows();
    showNotification(`Dependencies ${showDependencies ? 'shown' : 'hidden'}`, 'info');
}

function showNotification(message, type = 'info') {
    const notification = document.createElement('div');
    notification.className = `fixed top-4 right-4 p-4 rounded-lg shadow-lg z-50 ${
        type === 'success' ? 'bg-green-500 text-white' :
        type === 'error' ? 'bg-red-500 text-white' :
        'bg-blue-500 text-white'
    }`;
    notification.textContent = message;
    
    document.body.appendChild(notification);
    
    setTimeout(() => {
        notification.remove();
    }, 3000);
}

// Handle form submission
document.getElementById('addTaskForm').addEventListener('submit', function(e) {
    e.preventDefault();
    
    const formData = new FormData(this);
    const taskData = Object.fromEntries(formData);
    
    // Add new task to the array
    const newTask = {
        id: tasks.length + 1,
        name: taskData.name,
        assignee: taskData.assignee,
        start_date: taskData.start_date,
        end_date: taskData.end_date,
        progress: parseInt(taskData.progress),
        dependencies: taskData.dependencies ? taskData.dependencies.split(',') : [],
        color: 'bg-indigo-500'
    };
    
    tasks.push(newTask);
    
    // Refresh the Gantt chart
    initializeGantt();
    
    // Close modal and show success message
    closeAddTaskModal();
    showNotification('Task added successfully!', 'success');
});

// Initialize on page load
document.addEventListener('DOMContentLoaded', function() {
    initializeGantt();
});
</script>
@endsection
